package src._2024_02_14;

public enum Major {
    CONSTRUCTION,
    TOURISM,
    ECONOMICS,
    MANAGEMENT,
    APPLIED_INFORMATICS,
    PEDAGOGICAL_EDUCATION,
    BIOLOGY,
    SERVICE,
    SOFTWARE_ENGINEERING
}
